Main svc
kskripkin/java-explore-with-me pull request #3
Opened 2023-03-31 21:24 UTC by kskripkin

2023-04-01 20:02 UTC, sergeymamonov requested changes
В модуле http-client не должно быть пакетов controller и service (и всех классов, которые в этих пакетах). Эти классы уже есть в сервисе статистики.

Привел типовые ошибки, некоторые из них повторяются в коде более одного раза.

У полей моделей отсутствуют модификаторы доступа.

Проверьте, как во всем проекте вызывается метод equals()

2023-04-02 05:28 UTC, kskripkin commented on ewm-service/pom.xml
>      <dependencies>
Исправлено

2023-04-02 05:29 UTC, kskripkin commented on ewm-service/service/pom.xml
> +<!--    <properties>-->
Исправлено

2023-04-02 06:20 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/events/AdminEventsServiceImpl.java
> +            return eventRepository.getEvents(users, categories, PageRequest.of((from / size), size))
Исправлено во всех местах

2023-04-02 06:21 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/events/AdminEventsServiceImpl.java
> +        }
Исправил

2023-04-02 06:24 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/exception/ExceptionHandler.java
> +//    public ResponseEntity<String> handleThrowable(final Throwable e) {
Исправлено

2023-04-02 06:25 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/mapper/CustomerMapperImpl.java
> +//        if ( updateEventAdminRequest.getStateAction() != null ) {
Исправлено

2023-04-02 06:27 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/mapper/RequestMapper.java
> +    public ParticipationRequestDto RequestToParticipationRequestDto(Request request) {
Исправлено

2023-04-02 06:28 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/mapper/RequestMapper.java
> +    public EventRequestStatusUpdateRequest RequestToEventRequestStatusUpdateRequest(Request request) {
Убрал

2023-04-02 06:28 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/model/categories/NewCategoryDto.java
> +    String name;
Исправлено

2023-04-02 06:28 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/model/compilations/Compilation.java
> +    long id;
Исправлено

2023-04-02 06:28 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/model/compilations/CompilationDto.java
> +    long id;
Исправлено

2023-04-02 08:46 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/mapper/CustomerMapperImpl.java
> +            locationsRepository.save(new Location(
Исправлено

2023-04-02 08:47 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/mapper/EventMapper.java
> +    private final CategoriesRepository categoriesRepository;
Исправлено

2023-04-02 08:47 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/mapper/CompilationsMapper.java
> +                eventRepository.getEvents(compilation.getId())
Исправлено

2023-04-02 09:11 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +            compilationRepository.saveEventsToCompilation(compilation.getId(), eventId);
Исправлено

2023-04-02 09:13 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +            compilationRepository.saveEventsToCompilation(compId, eventId);
Исправлено

2023-04-02 10:01 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/validation/ValidateEvents.java
> +        if (statusSource.equals("PENDING")) {
Исправил + сделал проверку на null в БД

2023-04-02 19:11 UTC, sergeymamonov requested changes
stream в стрим API это и есть цикл по коллекции, поэтому если вы делаете в нем запрос к БД, то значит вы делаете запросы к БД в цикле. Это нужно исправить.

2023-04-02 19:11 UTC, sergeymamonov commented on ewm-service/service/src/main/java/ru/practicum/validation/ValidateEvents.java
> +        if (event.getParticipantLimit() == event.getConfirmedRequests()) {
Здесь лучше сравнить через equals(). Ошибки как сейчас не будет, так как сравниваются примитивы, но лучше использовать equals().

2023-04-02 19:11 UTC, sergeymamonov commented on ewm-service/service/src/main/java/ru/practicum/mapper/EventMapper.java
> +    private final CategoriesRepository categoriesRepository;
Запросы из конвертера в БД. В конвертере вообще не должно быть ни одного бина репозитория.

2023-04-02 19:11 UTC, sergeymamonov commented on ewm-service/service/src/main/java/ru/practicum/admin/events/AdminEventsServiceImpl.java
> +                            categoriesRepository.getById(x.getCategory()),
Запросы к БД в цикле.

2023-04-02 19:16 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/validation/ValidateEvents.java
> +            throw new ValidationException("size < 1");
Исправил

2023-04-02 19:24 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/validation/ValidateEvents.java
> +        if (event.getParticipantLimit() == event.getConfirmedRequests()) {
Сергей, тут сравниваются два значения примитива long. Для них equals() не применим. Или мне исправить эти примитивы на класс обертку Long в исходных сущностях?

2023-04-02 19:25 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/mapper/EventMapper.java
> +    private final CategoriesRepository categoriesRepository;
Исправил. В прошлый раз откатывал изменения и забыл вернуть на исправленную версию.

2023-04-02 19:54 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +                        categoriesRepository.getById(x.getCategory()),
Исправил

2023-04-02 19:54 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +                        categoriesRepository.getById(x.getCategory()),
Исправил

2023-04-02 20:07 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/events/AdminEventsServiceImpl.java
> +                            categoriesRepository.getById(x.getCategory()),
Исправил

2023-04-02 20:08 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/validation/ValidateEvents.java
> +        if (event.getParticipantLimit() == event.getConfirmedRequests()) {
Договорились или не править, или исправить в сущности тип на класс-обертку Long.

2023-04-04 03:58 UTC, sergeymamonov approved these changes

2023-04-04 03:58 UTC, sergeymamonov commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +        List<Long> categoryIdList = eventList.stream().map(x -> x.getCategory()).collect(Collectors.toList());
В лямбде, конечно, можно чуть проще называть переменные, но почему бы вместо x не назвать event?

2023-04-04 03:58 UTC, sergeymamonov commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +                        categoryList.stream().filter(v -> v.getId() == x.getCategory()).findFirst().get(),
При таком решении получается квадратичная сложно. То есть мы каждый раз проходим по всем спискам. Можно этого избежать, если выбрать другую структуру данных, из которой можно было бы брать нужное значение за константное время (О(1)).

2023-04-04 03:58 UTC, sergeymamonov commented on ewm-service/service/src/main/java/ru/practicum/mapper/EventMapper.java
> +    private final CategoriesRepository categoriesRepository;
По коду это не очень похоже на mapper, так как mapper один объект конвертирует в другой. Здесь же происходит создание объекта из данных. Поэтому это больше билдер или фабрика. И название у класса должно быть соответствующее. Не настаиваю на этом изменении, лишь наблюдение.

2023-04-04 03:58 UTC, sergeymamonov commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +                        locationList.stream().filter(v -> v.getId() == x.getLocation()).findFirst().get()
findFirst() возвращает Optional. Если в Optional будет null и вызвать без проверки get(), то будет NoSuchElementException. https://struchkov.dev/blog/ru/optional-in-java/

2023-04-04 17:25 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +        List<Long> categoryIdList = eventList.stream().map(x -> x.getCategory()).collect(Collectors.toList());
Исправил

2023-04-04 17:25 UTC, kskripkin commented on ewm-service/service/src/main/java/ru/practicum/admin/compilations/CompilationAdminServiceImpl.java
> +                        categoryList.stream().filter(v -> v.getId() == x.getCategory()).findFirst().get(),
Да, понял как. Спасибо. Исправил.

2023-04-04 17:29 UTC, merged